import Head from "next/head";
import Image from "next/image";
import {
  ApolloClient,
  InMemoryCache,
  ApolloProvider,
  gql,
} from "@apollo/client";
import styles from "../styles/Home.module.css";

const client = new ApolloClient({
  uri: "https://api.graphql.jobs/",
  cache: new InMemoryCache(),
});

export async function getServerSideProps() {
  const { data } = await client.query({
    query: gql`
      query jobs {
        jobs {
          id
          title
          slug
          commitment {
            title
          }
          cities {
            name
            country {
              isoCode
            }
          }
          countries {
            name
          }
          remotes {
            name
          }
          description
          applyUrl
          company {
            name
          }
          tags {
            name
          }
          isPublished
          isFeatured
          locationNames
          userEmail
          postedAt
          createdAt
          updatedAt
        }
      }
    `,
  });
  // .then((result) => console.log(result));

  return {
    props: {
      allJobs: data.jobs,
    },
  };
}

export default function Home({ allJobs }) {
  console.log("the jobs", allJobs);
  return (
    <div className={styles.container}>
      <Head>
        <title>JobBatical</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>List of GraphQL jobs</h1>

        {/* <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p> */}

        <div className={styles.grid}>
          {allJobs?.map((job) => (
            <div className={styles.card} key={job.id}>
              <div className={styles.column1}>
                <h1 className={styles.jobTitle}>{job.title}</h1>
                <p>{job.company.name}</p>
              </div>
              {job.tags?.slice(0, 3).map((tag) => (
                <div className={styles.tags} key={tag.id}>
                  <h3 className={styles.tag}>{tag.name}</h3>
                </div>
              ))}
              {/* <div>{job.locationNames}</div> */}
              {job.cities?.map((city) => (
                <div className={styles.column3} key={city.id}>
                  <h4>{city.name}</h4>
                  {/* {job.cities?.country?.map((country) => (
                    <div key={country.isoCode}>
                      {country.isoCode}
                      <img src={country.isoCode} />
                    </div>
                  ))} */}
                </div>
              ))}
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}
        <p>Page made by Laura Sacripanti for JobBatical</p>
      </footer>
    </div>
  );
}
